### ISSUE TITLE
"view" dropdown does not work for sample item

### ISSUE THREAD

**Issue by benburton** [PieElements/corespring-placement-ordering#7]
**Steps to Reproduce:**
1. Install [`pie-cli`](https://github.com/PieLabs/pie-cli)
2. Clone [`corespring-placement-ordering`](https://github.com/PieElements/corespring-placement-ordering)
3. `cd` into `corespring-placement-ordering/docs/demo`
5. Run `pie pack-question`
5. Run `pie serve-question`
6. Navigate to http://localhost:4000
7. In the `corespring-placement-ordering` question prompted by "Arrange the fruits alphabetically" enter an incorrect order (e.g., "Lemon", "Melon", "Blueberry", "Pear").
8. Click "gather" in the "view" drop down.

**Expected Behavior:** The drop down will drop down, revealing different changes for the view.

**Actual Behavior:** The drop down is cleared, and the choices are not displayed.
This is in the console:

    pie.js:42387 Uncaught TypeError: Cannot read property 'getLayer' of undefined
        at Popover._this.setPlacement (http://localhost:4000/pie.js:42387:28)
        at Popover.componentDidUpdate (http://localhost:4000/pie.js:42473:12)
        at measureLifeCyclePerf (http://localhost:4000/pie.js:112285:12)
        at http://localhost:4000/pie.js:112939:11
        at CallbackQueue.notifyAll (http://localhost:4000/pie.js:44582:22)
        at ReactReconcileTransaction.close (http://localhost:4000/pie.js:117358:26)
        at ReactReconcileTransaction.closeAll (http://localhost:4000/pie.js:9645:25)
        at ReactReconcileTransaction.perform (http://localhost:4000/pie.js:9592:16)
        at ReactUpdatesFlushTransaction.perform (http://localhost:4000/pie.js:9579:20)
        at ReactUpdatesFlushTransaction.perform (http://localhost:4000/pie.js:2440:32)

**NOTE:** I'm not sure if this is meant to be in this project, [`pie-cli`](https://github.com/pielabs/pie-cli) or [`pie-control-panel`](https://github.com/PieLabs/pie-control-panel)

**Comment by amiklosi** [comment]
This was due to react being included twice on the page, not sure what we should do to prevent it in general, now I just bumped the react version in the component to fix it.
